language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
before_deploy: npm install now --no-save
deploy:
  - provider: script
    script: cd build && now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: cd build && now --public --token $NOW_TOKEN && now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
